# Board A — echo client (192.168.1.1 → 192.168.1.2)
CONFIG_APP_ECHO_SERVER=n
CONFIG_APP_MY_IPV4_ADDR="192.168.1.1"
CONFIG_APP_PEER_IPV4_ADDR="192.168.1.2"

# IrDA half-duplex: offset retransmit timer from Board B
CONFIG_NET_L2_PPP_TIMEOUT=2000
